services:
  backend:
    build:
      context: ./BackEnd
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production 

  frontend:
    build:
      context: ./FrontEnd 
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend 

networks:
  app-network:
    driver: bridge
